services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hoogi91\Spreadsheets\:
    resource: '../Classes/*'

  Hoogi91\Spreadsheets\DataProcessing\SpreadsheetProcessor:
    public: true

  Hoogi91\Spreadsheets\DataProcessing\TabsProcessor:
    public: true

  Hoogi91\Spreadsheets\Hooks\DataHandlerHook:
    public: true

  Hoogi91\Spreadsheets\Service\ExtractorService:
    public: true

  Hoogi91\Spreadsheets\Service\ReaderService:
    public: true

  Hoogi91\Spreadsheets\Form\Element\DataInputElement:
    arguments:
      $readerService: '@Hoogi91\Spreadsheets\Service\ReaderService'
      $extractorService: '@Hoogi91\Spreadsheets\Service\ExtractorService'
      $view: '@TYPO3\CMS\Fluid\View\StandaloneView'
